"""Add setting table with sub_category

Revision ID: 427c80df52a1
Revises: 311f14d8cd0c
Create Date: 2026-04-13 09:29:26.720053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427c80df52a1'
down_revision: Union[str, Sequence[str], None] = '311f14d8cd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_setting_category'), 'setting', ['category'], unique=False)
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=False)
    op.create_index(op.f('ix_setting_sub_category'), 'setting', ['sub_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setting_sub_category'), table_name='setting')
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_index(op.f('ix_setting_category'), table_name='setting')
    op.drop_table('setting')
    # ### end Alembic commands ###
