"""Add Multi-site Resource management tables

Revision ID: e2d709321911
Revises: 427c80df52a1
Create Date: 2026-04-13 09:54:17.230997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d709321911'
down_revision: Union[str, Sequence[str], None] = '427c80df52a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_id'), 'clinic', ['id'], unique=False)
    op.create_index(op.f('ix_clinic_name'), 'clinic', ['name'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CONSULTATION', 'SURGERY', 'PRE_OP', 'IMAGING', 'HOSPITALIZATION', name='roomtype'), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_table('user_clinic',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'clinic_id')
    )
    op.create_table('hospitalization_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_reference', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CAGE', 'BOX', 'PARC', name='slottype'), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitalization_slot_id'), 'hospitalization_slot', ['id'], unique=False)
    op.add_column('client', sa.Column('favorite_clinic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'clinic', ['favorite_clinic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'favorite_clinic_id')
    op.drop_index(op.f('ix_hospitalization_slot_id'), table_name='hospitalization_slot')
    op.drop_table('hospitalization_slot')
    op.drop_table('user_clinic')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_clinic_name'), table_name='clinic')
    op.drop_index(op.f('ix_clinic_id'), table_name='clinic')
    op.drop_table('clinic')
    # ### end Alembic commands ###
